/**
 * `gcloud ... --help` for the commands an operator looks up during these tasks, in gcloud's own
 * layout. A command without a page here still gets gcloud's full structure (synopsis, wide flags),
 * never a two-line stub, which read as a mock. Group pages list the commands under them.
 */
const P = (synopsis, description, flags = [], positional = []) => ({ synopsis, description, flags, positional });
const LOC = ['--location=LOCATION', 'The location of the job. By default, uses the location of the current project\'s App Engine app if there is an associated app.'];
const PAGES = {
  'scheduler': P('gcloud scheduler GROUP [GCLOUD_WIDE_FLAG ...]', 'Manage Cloud Scheduler jobs and schedules.'),
  'scheduler jobs': P('gcloud scheduler jobs COMMAND [GCLOUD_WIDE_FLAG ...]', 'Manage Cloud Scheduler jobs.'),
  'scheduler jobs list': P('gcloud scheduler jobs list [--location=LOCATION] [--filter=EXPRESSION] [--limit=LIMIT] [--page-size=PAGE_SIZE] [--sort-by=[FIELD,...]] [--uri] [GCLOUD_WIDE_FLAG ...]', 'List jobs.', [LOC]),
  'scheduler jobs describe': P('gcloud scheduler jobs describe (JOB : --location=LOCATION) [GCLOUD_WIDE_FLAG ...]', 'Show details about a job.', [LOC], ['JOB', 'ID of the job or fully qualified identifier for the job.']),
  'scheduler jobs pause': P('gcloud scheduler jobs pause (JOB : --location=LOCATION) [GCLOUD_WIDE_FLAG ...]', 'Pause execution of a job.', [LOC], ['JOB', 'ID of the job or fully qualified identifier for the job.']),
  'scheduler jobs resume': P('gcloud scheduler jobs resume (JOB : --location=LOCATION) [GCLOUD_WIDE_FLAG ...]', 'Resume execution of a job.', [LOC], ['JOB', 'ID of the job or fully qualified identifier for the job.']),
  'scheduler jobs run': P('gcloud scheduler jobs run (JOB : --location=LOCATION) [GCLOUD_WIDE_FLAG ...]', 'Run a job.', [LOC], ['JOB', 'ID of the job or fully qualified identifier for the job.']),
  'scheduler jobs delete': P('gcloud scheduler jobs delete (JOB : --location=LOCATION) [GCLOUD_WIDE_FLAG ...]', 'Delete a job.', [LOC], ['JOB', 'ID of the job or fully qualified identifier for the job.']),
  'scheduler jobs update': P('gcloud scheduler jobs update COMMAND [GCLOUD_WIDE_FLAG ...]', 'Update Cloud Scheduler jobs.'),
  'scheduler jobs update app-engine': P('gcloud scheduler jobs update app-engine (JOB : --location=LOCATION) [--schedule=SCHEDULE] [--time-zone=TIME_ZONE] [--description=DESCRIPTION] [GCLOUD_WIDE_FLAG ...]', 'Update a Cloud Scheduler job with an App Engine target.', [LOC, ['--schedule=SCHEDULE', 'Schedule on which the job will be executed.'], ['--time-zone=TIME_ZONE', 'Specifies the time zone to be used in interpreting --schedule.']]),
  'scheduler jobs update http': P('gcloud scheduler jobs update http (JOB : --location=LOCATION) [--attempt-deadline=ATTEMPT_DEADLINE] [--description=DESCRIPTION] [--schedule=SCHEDULE] [--time-zone=TIME_ZONE] [--uri=URI] [--http-method=HTTP_METHOD] [--message-body=MESSAGE_BODY | --message-body-from-file=PATH] [--oidc-service-account-email=OIDC_SERVICE_ACCOUNT_EMAIL] [GCLOUD_WIDE_FLAG ...]', 'Update a Cloud Scheduler job with an HTTP target.', [LOC, ['--schedule=SCHEDULE', 'Schedule on which the job will be executed, in unix-cron format.'], ['--time-zone=TIME_ZONE', 'Specifies the time zone to be used in interpreting --schedule.'], ['--uri=URI', 'The full URI path that the request will be sent to.'], ['--http-method=HTTP_METHOD', 'HTTP method to use for the request. HTTP_METHOD must be one of: delete, get, head, post, put.']], ['JOB', 'ID of the job or fully qualified identifier for the job.']),
  'scheduler jobs update pubsub': P('gcloud scheduler jobs update pubsub (JOB : --location=LOCATION) [--schedule=SCHEDULE] [--time-zone=TIME_ZONE] [--topic=TOPIC] [GCLOUD_WIDE_FLAG ...]', 'Update a Cloud Scheduler job with a Pub/Sub target.', [LOC]),
  'run': P('gcloud run GROUP | COMMAND [GCLOUD_WIDE_FLAG ...]', 'Manage your Cloud Run applications.'),
  'run jobs': P('gcloud run jobs COMMAND [GCLOUD_WIDE_FLAG ...]', 'View and manage your Cloud Run jobs.'),
  'run jobs describe': P('gcloud run jobs describe (JOB : --region=REGION) [GCLOUD_WIDE_FLAG ...]', 'Obtain details about jobs.', [['--region=REGION', 'Region in which the resource can be found.']]),
  'run jobs update': P('gcloud run jobs update (JOB : --region=REGION) [--image=IMAGE] [--tasks=TASKS] [--task-timeout=TASK_TIMEOUT] [--max-retries=MAX_RETRIES] [--update-env-vars=[KEY=VALUE,...]] [--remove-env-vars=[KEY,...]] [--set-env-vars=[KEY=VALUE,...]] [--execute-now] [--wait] [GCLOUD_WIDE_FLAG ...]', 'Update a Cloud Run Job.', [['--image=IMAGE', 'Name of the container image to deploy.'], ['--update-env-vars=[KEY=VALUE,...]', 'List of key-value pairs to set as environment variables.'], ['--set-env-vars=[KEY=VALUE,...]', 'List of key-value pairs to set as environment variables. All existing environment variables will be removed first.'], ['--region=REGION', 'Region in which the resource can be found.']]),
  'run jobs executions': P('gcloud run jobs executions COMMAND [GCLOUD_WIDE_FLAG ...]', 'Manage your Cloud Run jobs executions.'),
  'run jobs executions list': P('gcloud run jobs executions list [--job=JOB] [--region=REGION] [--filter=EXPRESSION] [--limit=LIMIT] [GCLOUD_WIDE_FLAG ...]', 'List executions.'),
  'sql': P('gcloud sql GROUP [GCLOUD_WIDE_FLAG ...]', 'Create and manage Google Cloud SQL databases.'),
  'sql instances': P('gcloud sql instances COMMAND [GCLOUD_WIDE_FLAG ...]', 'Provide commands for managing Cloud SQL instances.'),
  'sql instances describe': P('gcloud sql instances describe INSTANCE [GCLOUD_WIDE_FLAG ...]', 'Displays configuration and metadata about a Cloud SQL instance.', [], ['INSTANCE', 'Cloud SQL instance ID.']),
  'sql instances restart': P('gcloud sql instances restart INSTANCE [--async] [GCLOUD_WIDE_FLAG ...]', 'Restarts a Cloud SQL instance.', [['--async', 'Return immediately, without waiting for the operation in progress to complete.']], ['INSTANCE', 'Cloud SQL instance ID.']),
  'sql instances patch': P('gcloud sql instances patch INSTANCE [--async] [--database-flags=FLAG=VALUE,[FLAG=VALUE,...] | --clear-database-flags] [--tier=TIER, -t TIER] [--maintenance-window-day=DAY] [--backup-start-time=BACKUP_START_TIME] [--diff] [GCLOUD_WIDE_FLAG ...]', 'Updates the settings of a Cloud SQL instance.', [['--database-flags=FLAG=VALUE,[FLAG=VALUE,...]', 'Comma-separated list of database flags to set on the instance. Use an equals sign to separate flag name and value. Flags without values, like skip_grant_tables, can be written out without a value after, e.g., `skip_grant_tables=`. Use on/off for booleans. View the Instance Resource API for allowed flags. (e.g., --database-flags max_allowed_packet=55555,skip_grant_tables=,log_output=1)'], ['--clear-database-flags', 'Clear the database flags set on the instance. WARNING: Instance will be restarted.'], ['--diff', 'Show what changed as a result of the update.']], ['INSTANCE', 'Cloud SQL instance ID.']),
  'sql backups': P('gcloud sql backups COMMAND [GCLOUD_WIDE_FLAG ...]', 'Provide commands for working with backups of Cloud SQL instances.'),
  'sql backups create': P('gcloud sql backups create --instance=INSTANCE, -i INSTANCE [--async] [--description=DESCRIPTION] [--location=LOCATION] [GCLOUD_WIDE_FLAG ...]', 'Creates a backup of a Cloud SQL instance.', [['--instance=INSTANCE, -i INSTANCE', 'Cloud SQL instance ID.'], ['--async', 'Return immediately, without waiting for the operation in progress to complete.'], ['--description=DESCRIPTION', 'A friendly description of the backup.']]),
  'storage': P('gcloud storage GROUP | COMMAND [GCLOUD_WIDE_FLAG ...]', 'Create and manage Cloud Storage buckets and objects.'),
  'storage buckets': P('gcloud storage buckets COMMAND [GCLOUD_WIDE_FLAG ...]', 'Manage Cloud Storage buckets.'),
  'storage buckets create': P('gcloud storage buckets create URL [URL ...] [--no-async] [--default-storage-class=DEFAULT_STORAGE_CLASS, -c DEFAULT_STORAGE_CLASS, -s DEFAULT_STORAGE_CLASS] [--location=LOCATION, -l LOCATION] [--public-access-prevention, --pap] [--retention-period=RETENTION_PERIOD] [--uniform-bucket-level-access, -b] [GCLOUD_WIDE_FLAG ...]', 'Create buckets for storing objects.', [['--location=LOCATION, -l LOCATION', 'Location (https://cloud.google.com/storage/docs/locations) for the bucket. If not specified, the location used by Cloud Storage is us.'], ['--default-storage-class=DEFAULT_STORAGE_CLASS, -c DEFAULT_STORAGE_CLASS, -s DEFAULT_STORAGE_CLASS', 'Default storage class for the bucket.'], ['--uniform-bucket-level-access, -b', 'Turns on uniform bucket-level access setting. Default is False.'], ['--public-access-prevention, --pap', 'Sets public access prevention to "enforced".']], ['URL [URL ...]', 'The URLs of the buckets to create.']),
  'storage buckets update': P('gcloud storage buckets update URL [URL ...] [--versioning | --no-versioning] [--lifecycle-file=LIFECYCLE_FILE | --clear-lifecycle] [--update-labels=[KEY=VALUE,...]] [--uniform-bucket-level-access] [GCLOUD_WIDE_FLAG ...]', 'Update bucket settings.'),
  'storage buckets describe': P('gcloud storage buckets describe URL [--raw] [GCLOUD_WIDE_FLAG ...]', 'Describes Cloud Storage buckets.'),
  'storage buckets add-iam-policy-binding': P('gcloud storage buckets add-iam-policy-binding URL --member=PRINCIPAL --role=ROLE [--condition=[KEY=VALUE,...] | --condition-from-file=CONDITION_FROM_FILE] [GCLOUD_WIDE_FLAG ...]', 'Add an IAM policy binding to a bucket.', [['--member=PRINCIPAL', 'The principal to add the binding for. Should be of the form user|group|serviceAccount:email or domain:domain.'], ['--role=ROLE', 'Role name to assign to the principal.']]),
  'storage buckets notifications create': P('gcloud storage buckets notifications create URL [--custom-attributes=[KEY=VALUE,...]] [--event-types=[NOTIFICATION_EVENT_TYPE,...], -e [NOTIFICATION_EVENT_TYPE,...]] [--object-prefix=OBJECT_PREFIX, -p OBJECT_PREFIX] [--payload-format=PAYLOAD_FORMAT, -f PAYLOAD_FORMAT] [--skip-topic-setup, -s] [--topic=TOPIC, -t TOPIC] [GCLOUD_WIDE_FLAG ...]', 'Create a notification configuration on a bucket.'),
  'storage cp': P('gcloud storage cp [SOURCE ...] DESTINATION [--all-versions, -A] [--no-clobber, -n] [--recursive, -R, -r] [--preserve-posix, -P] [GCLOUD_WIDE_FLAG ...]', 'Upload, download, and copy Cloud Storage objects.'),
  'storage rsync': P('gcloud storage rsync SOURCE DESTINATION [--delete-unmatched-destination-objects] [--dry-run] [--exclude=[REGEX,...], -x [REGEX,...]] [--recursive, -R, -r] [GCLOUD_WIDE_FLAG ...]', 'Synchronize content of two buckets/directories.', [['--delete-unmatched-destination-objects', 'Delete extra files under DESTINATION not found under SOURCE. By default extra files are not deleted. Note: this option can delete data quickly if you specify the wrong source and destination combination.'], ['--dry-run', 'Print operations rsync would perform without actually performing them.'], ['--recursive, -R, -r', 'Recursively copy the contents of any directories that match the source path expression.']]),
  'compute backend-buckets update': P('gcloud compute backend-buckets update BACKEND_BUCKET_NAME [--description=DESCRIPTION] [--gcs-bucket-name=GCS_BUCKET_NAME] [--[no-]enable-cdn] [GCLOUD_WIDE_FLAG ...]', 'Update a backend bucket.', [['--gcs-bucket-name=GCS_BUCKET_NAME', 'The name of the Google Cloud Storage bucket to serve from. The storage bucket must be owned by the project\'s owner.']]),
  'container clusters get-credentials': P('gcloud container clusters get-credentials NAME [--internal-ip] [--location=LOCATION | --region=REGION | --zone=ZONE, -z ZONE] [GCLOUD_WIDE_FLAG ...]', 'Fetch credentials for a running cluster.', [['--region=REGION', 'Compute region (e.g. us-central1) for a regional cluster.']], ['NAME', 'Name of the cluster to get credentials for.']),
  'logging read': P('gcloud logging read [LOG_FILTER] [--folder=FOLDER_ID | --organization=ORGANIZATION_ID | --project=PROJECT_ID] [--freshness=FRESHNESS; default="1d"] [--order=ORDER; default="desc"] [--limit=LIMIT] [GCLOUD_WIDE_FLAG ...]', 'Read log entries.', [['--freshness=FRESHNESS; default="1d"', 'Return entries that are not older than this value. Works only with DESC ordering and filters without a timestamp.'], ['--limit=LIMIT', 'Maximum number of resources to list.']]),
};
/** One-line summaries shown in a group's COMMANDS list. */
const SUMMARY = (key) => PAGES[key]?.description ?? '';
const WIDE = ['GCLOUD WIDE FLAGS', '    These flags are available to all commands: --access-token-file, --account,', '    --billing-project, --configuration, --flags-file, --flatten, --format,', '    --help, --impersonate-service-account, --log-http, --project, --quiet,', '    --trace-token, --user-output-enabled, --verbosity.', '', '    Run $ gcloud help for details.'];

export function helpPage(words) {
  const key = words.join(' ');
  const page = PAGES[key];
  const children = Object.keys(PAGES).filter(k => k.startsWith(`${key} `) && k.split(' ').length === words.length + 1);
  const summary = (page?.description ?? `${words.at(-1)} ${words.slice(0, -1).at(-1) ?? ''}`).replace(/\.$/, '');
  const out = ['NAME', `    gcloud ${key} - ${summary[0].toLowerCase()}${summary.slice(1)}`, '', 'SYNOPSIS', `    ${page?.synopsis ?? `gcloud ${key} ${children.length ? 'COMMAND' : '[FLAGS]'} [GCLOUD_WIDE_FLAG ...]`}`, ''];
  if (page) out.push('DESCRIPTION', `    ${page.description}`, '');
  if (page?.positional?.length) out.push('POSITIONAL ARGUMENTS', `     ${page.positional[0]}`, `        ${page.positional[1]}`, '');
  if (page?.flags?.length) { out.push('FLAGS'); for (const [f, d] of page.flags) out.push(`     ${f}`, ...wrap(d, 8), ''); }
  out.push(...WIDE, '');
  if (children.length) { out.push(words.length === 1 ? 'GROUPS' : 'COMMANDS', `    ${words.length === 1 ? 'GROUP' : 'COMMAND'} is one of the following:`, ''); for (const c of children) out.push(`     ${c.split(' ').pop()}`, ...wrap(SUMMARY(c), 8), ''); }
  out.push('NOTES', '    These variants are also available:', '', `        $ gcloud alpha ${key}`, '', `        $ gcloud beta ${key}`);
  return out;
}
function wrap(text, indent) {
  const out = [];
  let line = '';
  for (const w of text.split(' ')) { if ((line + w).length > 80 - indent && line) { out.push(' '.repeat(indent) + line.trimEnd()); line = ''; } line += `${w} `; }
  if (line.trim()) out.push(' '.repeat(indent) + line.trimEnd());
  return out;
}
